server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/hjdb?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: Mysql@123456
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: MULTI_ACCOUNTING
#  config:
#    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}